name: Continuous integration

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
          target: thumbv8m.main-none-eabihf

      - name: Install GCC ARM
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi

      - name: Cargo Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=thumbv8m.main-none-eabihf

      - name: Cargo Build Examples
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --target=thumbv8m.main-none-eabihf

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
