on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
          target: thumbv8m.main-none-eabihf

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=thumbv8m.main-none-eabihf

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples --target=thumbv8m.main-none-eabihf

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
